ros_impedance_controller:
  type: ros_impedance_controller/Controller
  joints:
    - lf_haa_joint
    - lf_hfe_joint
    - lf_kfe_joint
    - rf_haa_joint
    - rf_hfe_joint
    - rf_kfe_joint
    - lh_haa_joint
    - lh_hfe_joint
    - lh_kfe_joint
    - rh_haa_joint
    - rh_hfe_joint
    - rh_kfe_joint
    - z_back_wheel_joint
    - z_front_wheel_joint
    - z_left_wheel_joint
    - z_right_wheel_joint
  gains:
      lf_haa_joint: {p: 10.0, i: 0.0, d: 1.0}
      lf_hfe_joint: {p: 5.0, i: 0.0, d: 0.5}
      lf_kfe_joint: {p: 1.0, i: 0.0, d: 0.01}

      rf_haa_joint: {p: 10.0, i: 0.0, d: 1.0}
      rf_hfe_joint: {p: 5.0, i: 0.0, d: 0.5}
      rf_kfe_joint: {p: 1.0, i: 0.0, d: 0.01}

      lh_haa_joint: {p: 10.0, i: 0.0, d: 1.0}
      lh_hfe_joint: {p: 5.0, i: 0.0, d: 0.5}
      lh_kfe_joint: {p: 1.0, i: 0.0, d: 0.01}

      rh_haa_joint: {p: 10.0, i: 0.0, d: 1.0}
      rh_hfe_joint: {p: 5.0, i: 0.0, d: 0.5}
      rh_kfe_joint: {p: 1.0, i: 0.0, d: 0.01}

      z_back_wheel_joint: {p: 10.0, i: 0.0, d: 0.1}
      z_front_wheel_joint: {p: 10.0, i: 0.0, d: 0.1}
      z_left_wheel_joint: {p: 10.0, i: 0.0, d: 0.1}
      z_right_wheel_joint: {p: 10.0, i: 0.0, d: 0.1}


