ros_impedance_controller:
  type: ros_impedance_controller/Controller
  joints:
    - mountain_wire_pitch
    - mountain_wire_roll
    - mountain_wire_yaw
    - wire_base_prismatic 
    - wire_base_pitch
    - wire_base_roll 
    - wire_base_yaw 
    - hipitch 
    - hiproll 
    - knee 

  gains:
      mountain_wire_pitch: {p: 0.0, i: 0.0, d: 0}
      mountain_wire_roll: {p: 0.0, i: 0.0, d: 0}
      mountain_wire_yaw: {p: 0.0, i: 0.0, d: 0}
      wire_base_prismatic: {p: 0.0, i: 0.0, d: 0}
      wire_base_pitch: {p: 0.0, i: 0.0, d: 0}
      wire_base_roll: {p: 0.0, i: 0.0, d: 0}
      wire_base_yaw: {p: 0.0, i: 0.0, d: 0}
      hipitch: {p: 0.0, i: 0.0, d: 0}
      hiproll: {p: 0.0, i: 0.0, d: 0}
      knee: {p: 0.0, i: 0.0, d: 0}


  home:
      mountain_wire_pitch: 0.0
      mountain_wire_roll: 0.0
      mountain_wire_yaw: 0.0
      wire_base_prismatic: 0
      wire_base_pitch: 0
      wire_base_roll: 0
      wire_base_yaw: 0
      hipitch: 0
      hiproll: 0
      knee: 0
 
